### ISSUE TITLE
Unable to delete skills on dev

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#1055] opened 2020-11-06 15:18 UTC
**Describe the bug**
Unable to delete skills on dev 
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/21133129/98382542-578c0f00-2019-11eb-9229-f02db2804a37.png)
![image](https://user-images.githubusercontent.com/21133129/98382563-5d81f000-2019-11eb-937c-58511538e931.png)
![image](https://user-images.githubusercontent.com/21133129/98382603-683c8500-2019-11eb-9ef3-de446614d302.png)

**Additional context**

**Comment by mo-5** [comment] 2020-11-06 15:19
The issue is occurring with all tables in admin. unable to delete any elements.

**Comment by BenJeau** [comment] 2020-11-06 22:23
I'm curious, what is the request sent from the frontend, aka what is the backend receiving?

**Comment by BenJeau** [comment] 2020-11-09 23:09
I just tried locally on dev and this doesn't seem to be an issue for me for any of the tables
![Peek 2020-11-09 18-09](https://user-images.githubusercontent.com/22248828/98607191-ac988100-22b6-11eb-81fa-4a2199943e22.gif)

**Comment by Mousto097** [comment] 2020-11-10 00:07
@BenJeau I was not able to test it yet, I cannot access the Admin page in I-Talent (running locally). But I can access it on UAT. Can you please check if I have Admin Privileges on DEV?

<img width="275" alt="Screen Shot 2020-11-09 at 7 09 34 PM" src="https://user-images.githubusercontent.com/29315512/98611059-26346d00-22bf-11eb-83ab-8c6a1712a730.png">

@MohamedRadwan Since you have Admin Privileges can you please test again, if there are no issues deleting items, let's close this ticket. 

Thanks!

**Comment by BenJeau** [comment] 2020-11-10 00:16
I've been trying to add Suku and you for the last week, but the keycloak web interface is bugging out. I reached out to someone at ISED to give you the admin permission

**Comment by Mousto097** [comment] 2020-11-10 00:52
@BenJeau Thanks

**Comment by mo-5** [comment] 2020-11-10 01:50
@BenJeau Just tried it on dev and still getting an error 
![image](https://user-images.githubusercontent.com/21133129/98617468-0e63e580-22cd-11eb-89fe-51f8523cbdcc.png)
![image](https://user-images.githubusercontent.com/21133129/98617505-23d90f80-22cd-11eb-9fde-5b7dee30829f.png)
The delete request seems to be missing the uuid for the element it wants to delete

**Comment by BenJeau** [comment] 2020-11-10 02:38
Oh you're right, I don't know how it was working for me earlier..

**Comment by BenJeau** [comment] 2020-11-10 02:42
Oh it was working on this branch/PR #1045, I think that that PR somehow fixes it, maybe it was related to one of the frontend packages

**Comment by mo-5** [comment] 2020-11-10 02:53
Maybe ? But it would seem like an issue with our API call. I am not entirely sure.

**Comment by BenJeau** [comment] 2020-11-10 03:24
It used to work, I think its potentially related to axios, but it doesn't seem like they fixed anything related to our bug - but I guess you never know. Feel free to test the PR and check at the same time this bug

**Comment by BenJeau** [comment] 2020-11-15 18:46
Closing this, since I'm unable to reproduce it on OpenShift or locally since the #1045 PR. Feel free to reopen it if you still encounter it

**Closed as completed by BenJeau** 2020-11-15 18:46 UTC
Labels: :lady_beetle: bug, :warning: high priority
